name: validator
description: A starting point for Dart libraries or applications.
version: 1.0.0-alpha+3
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.1 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.0
